baseURL : "https://alecstuarteastman.com/"
languageCode: "en-us"
title : "A.S.E."
theme : "papermod_edit"

params:
    profileMode:
        enabled: true
        title: "Welcome to our Slash Project" 
        subtitle: "Please click the button below to proceed to our project page:"
        buttons:
            - name: RidOf
              url: "https://2733-185-199-104-14.eu.ngrok.io/"