baseURL : "https://alecstuarteastman.com/"
languageCode: "en-us"
title : "A.S.E."
theme : "PaperMod"

params:
    profileMode:
        enabled: true
        title: "Hi, I'm Alec 👋" 
        subtitle: "A software engineer living and studying in Berlin, Germany."
        imageUrl: "profile_pic.png" 
        imageWidth: 120 
        imageHeight: 120 
        buttons:
            - name: Projects
              url: "/archive"
            - name: Github
              url: "https://github.com/alecmalloc"